import type { Metadata } from 'next';
import { inter } from '@/src/lib/utils/fonts';
import '../globals.css';
import Header from '@/src/components/shared/Header';

import SideNav from '@/src/components/shared/SideNav';
import Footer from '@/src/components/shared/Footer';

export const metadata: Metadata = {
	title: 'cEDH-Stats',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${inter.className} antialiased`}>
				<main>
					<div className='flex h-screen flex-col md:flex-row md:overflow-hidden'>
						<SideNav />

						<section className='flex-grow p-6 md:overflow-y-auto md:p-12 bg-gradient-to-r bg-cedh-blue to-indigo-700'>
							{children}
						</section>
					</div>
				</main>
				{/* <Footer /> */}
			</body>
		</html>
	);
}
